/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.View;

/**
 *
 * @author Ivor
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRiba = new javax.swing.JButton();
        btnRibnjak = new javax.swing.JButton();
        btnRibar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RIBA");

        btnRiba.setText("Riba");
        btnRiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRibaActionPerformed(evt);
            }
        });

        btnRibnjak.setText("Ribnjak");
        btnRibnjak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRibnjakActionPerformed(evt);
            }
        });

        btnRibar.setText("Ribar");
        btnRibar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRibarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnRiba)
                .addGap(49, 49, 49)
                .addComponent(btnRibnjak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnRibar)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRiba)
                    .addComponent(btnRibnjak)
                    .addComponent(btnRibar))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRibaActionPerformed
new FormaRiba().setVisible(true);    }//GEN-LAST:event_btnRibaActionPerformed

    private void btnRibnjakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRibnjakActionPerformed

        new FormaRibnjak().setVisible(true);
        
    }//GEN-LAST:event_btnRibnjakActionPerformed

    private void btnRibarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRibarActionPerformed
new FormaRibar().setVisible(true);    }//GEN-LAST:event_btnRibarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRiba;
    private javax.swing.JButton btnRibar;
    private javax.swing.JButton btnRibnjak;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
